disabled_rules:
- trailing_whitespace
opt_in_rules:
- empty_count
- empty_string
# analyzer_rules: # rules run by `swiftlint analyze`
#   - explicit_self
# included: # case-sensitive paths to include during linting. `--path` is ignored if present
#   - Source
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
line_length:
    warning: 100
    error: 110
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 400
file_length:
    warning: 500
    error: 1200
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode"
